---
- name: Set up AD
  hosts: "{{ VCENTER_PDC_NAME }}.lab.local"

  tasks:
  - name: Lage OU
    win_shell: NEW-ADOrganizationalUnit "{{ VCENTER_MILJO }}" –path "OU=Grupper,DC=LAB,DC=LOCAL"
  - name: Lage AD gruppe
    win_shell: NEW-ADGroup –name "{{ VCENTER_MILJO }}" –groupscope Global –path OU="{{ VCENTER_MILJO }}",OU=Grupper,DC=LAB,DC=LOCAL