---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
    #  hostname: "{{ VCENTER_HOST }}"
    #  username: "{{ VCENTER_USERNAME }}"
    #  password: "{{ VCENTER_PASSWORD }}"
      validate_certs: False
      name: "{{ VCENTER_GUEST_NAME_2 }}"
      template: "{{ VCENTER_TEMPLATE }}"
      datacenter: "{{ VCENTER_DATACENTER }}"
      datastore: "{{ VCENTER_DATASTORE }}"
      folder: "{{ VCENTER_FOLDER }}"
      cluster: "{{ VCENTER_CLUSTER }}"
      hardware:
        memory_mb: "{{ vcenter_memory_mb }}"
        num_cpus: "{{ vcenter_cpus }}"
      wait_for_ip_address: yes
      customization:
        not: important
      customization_spec: "{{ VCENTER_GUEST_DOMAIN }}"
      state: poweredon