---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ VCENTER_HOST }}"
      username: "{{ VCENTER_USERNAME }}"
      password: "{{ VCENTER_PASSWORD }}"
      validate_certs: False
      name: "{{ VCENTER_GUEST_NAME }}"
      template: "{{ VCENTER_TEMPLATE }}"
      datacenter: "{{ VCENTER_DATACENTER }}"
      folder: "{{ VCENTER_FOLDER }}"
      cluster: "{{ VCENTER_CLUSTER }}"
      wait_for_ip_address: yes
      customization:
        not: important
      customization_spec: "hostname-win"
      state: poweredon