---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_package:
      path: \\pdc\delt\install\BTS_2016_Dev\BizTalkServer\LOB\Msi\Microsoft_BizTalk_Adapters_for_Enterprise_Applications.msi
      arguments: /passive /quiet /qn