---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install Scheduled Adapter
    win_package:
      path: \\pdc\delt\install\Biztalk-Deploy-master\bin\ScheduledTaskAdapter.msi
      arguments: /passive /quiet /qn