---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install Entsso
    win_command: \\pdc\delt\install\BTS_2016_Dev\BizTalkServer\setup.exe /NORESTART /CABPATH \\pdc\delt\install\Biztalk-Deploy-master\bin\BtsRedistW2K12R2EN64\BtsRedistW2K12R2EN64.cab /S \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\features-full.xml /L c:\log.txt 