---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_package:
      path: \\pdc\delt\install\BTS_2016_Dev\BizTalkServer\ASDK_x86\AdaptersSetup.msi
      arguments: /i /qn