---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install vcredist x64
    win_command: \\pdc\delt\install\Biztalk-Deploy-master\bin\VCRedist\x64\vcredist.exe /install /passive