---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"
    
  tasks:
  - name: Install .Net 2.0
    win_shell: powershell.exe Install-WindowsFeature Net-Framework-Core -source \\pdc\delt\install\Biztalk-Deploy-master\bin\sxs\sxs
  - name: Install Biztalk pre. features
    win_shell: Install-WindowsFeature -name FS-FileServer,Storage-Services,Web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,Web-Http-Logging,Web-Log-Libraries,Web-ODBC-Logging,Web-Request-Monitor,Web-Http-Tracing,Web-Stat-Compression,Web-Dyn-Compression,Web-Filtering,Web-Basic-Auth,Web-Digest-Auth,Web-Windows-Auth,Web-App-Dev,Web-Mgmt-Tools,NET-Framework-45-Core,NET-Framework-45-ASPNET,NET-WCF-HTTP-Activation45,NET-WCF-TCP-PortSharing45,RDC,RSAT-AD-PowerShell,RSAT-AD-AdminCenter,RSAT-ADDS-Tools,RSAT-ADLDS,FS-SMB1,PowerShell,PowerShell-V2,PowerShell-ISE,WAS-Process-Model,WAS-Config-APIs,WoW64-Support -IncludeAllSubFeature