---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install Scheduled Adapter
    win_command: \\pdc\delt\install\Biztalk-Deploy-master\bin\ScheduledTaskAdapter.msi /passive