---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_shell: 'c:\Program Files (x86)\Microsoft BizTalk Server 2016\Configuration.exe' /S \\pdc\delt\"{{ VCENTER_MILJO }}"BizTalkConfig_esso.xml /noprogressbar /L c:\sso-log.txt
    #args:
    #  chdir: c:\Program Files (x86)\Microsoft BizTalk Server 2016\