---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install .Net 2.0
    win_shell: powershell.exe Install-WindowsFeature Net-Framework-Core -source \\pdc\delt\install\Biztalk-Deploy-master\bin\sxs\sxs
  - name: Install vcredist x64
    win_shell: \\pdc\delt\install\Biztalk-Deploy-master\bin\VCRedist\x64\vcredist.exe /install /passive
  - name: Install vcresist x86
    win_shell: \\pdc\delt\install\Biztalk-Deploy-master\bin\VCRedist\x86\vcredist.exe /install /passive
  - name: Install Entsso
    win_shell: “\\pdc\delt\install\BTS_2016_Dev\BizTalk Server\setup.exe” /PASSIVE /NORESTART /CABPATH \\pdc\delt\install\Biztalk-Deploy-master\bin\BtsRedistW2K12R2EN64\BtsRedistW2K12R2EN64.cab /ADDLOCAL SSOAdmin,SSOSERVER
  - name: Install Biztalk features
    win_shell: “\\pdc\delt\install\BTS_2016_Dev\BizTalk Server\setup.exe” /PASSIVE /NORESTART /CABPATH \\pdc\delt\install\Biztalk-Deploy-master\bin\BtsRedistW2K12R2EN64\BtsRedistW2K12R2EN64.cab /ADDLOCAL BizTalk,WMI,AdminAndMonitoring,AdminTools,BAMTools,BizTalkAdminSnapIn,HealthActivityClient,MonitoringAndTracking,PAM,Documentation,BizTalk,WMI,Engine,MOT,MSMQ,Runtime
  - name: Configure Biztalk
    win_shell: “C:\Program Files (x86)\Microsoft BizTalk Server 2016\Configuration.exe” /S \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\BizTalkConfig.xml