---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"
  
  tasks:
  - name: Configure Biztalk
    win_package:
      path: '\\pdc\delt\install\BTS_2016_Dev\BizTalkServer\ESBT_x64\BizTalk ESB Toolkit 2.4.msi'
      arguments: /passive /quiet /qn