---
- name: Lage konfigurasjonsfil for  ENTSSO og biztalk
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\BizTalkConfig_esso.xml -Raw) -replace 'servernavn','{{ VCENTER_GUEST_NAME_2 }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'PASSORD_BACKUP_SECRET','{{ VCENTER_PASSORD_BACKUP_SECRET }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'BRUKERNAVN_ENTSSO_SERVICE','{{ VCENTER_BRUKERNAVN_ENTSSO_SERVICE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'DOMENE_NAVN','{{ VCENTER_DOMENE_NAVN }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'ENTSSO_PASSORD','{{ VCENTER_ENTSSO_PASSORD }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'ENTSSO_BACKUP_SECRET_FIL_STI','{{ VCENTER_ENTSSO_BACKUP_SECRET_FILE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'GROUP_SSO_ADMINISTRATORS','{{ VCENTER_GROUP_SSO_ADMINISTRATORS }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Lager konfigurasjon for  ENTSSO
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'GROUP_SSO_AFFILIATE_ADMINISTRATORS','{{ VCENTER_GROUP_SSO_AFFILIATE_ADMINISTRATORS }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml  
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\BizTalkConfig_biz.xml -Raw) -replace 'servernavn','{{ VCENTER_GUEST_NAME_2 }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'PASSORD_BACKUP_SECRET','{{ VCENTER_PASSORD_BACKUP_SECRET }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BRUKERNAVN_ENTSSO_SERVICE','{{ VCENTER_BRUKERNAVN_ENTSSO_SERVICE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'DOMENE_NAVN','{{ VCENTER_DOMENE_NAVN }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'ENTSSO_PASSORD','{{ VCENTER_ENTSSO_PASSORD }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'ENTSSO_BACKUP_SECRET_FIL_STI','{{ VCENTER_ENTSSO_BACKUP_SECRET_FILE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'GROUP_SSO_ADMINISTRATORS','{{ VCENTER_GROUP_SSO_ADMINISTRATORS }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'GROUP_SSO_AFFILIATE_ADMINISTRATORS','{{ VCENTER_GROUP_SSO_AFFILIATE_ADMINISTRATORS }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BIZTALK_ADMINISTRATOR_GROUP','{{ VCENTER_BIZTALK_ADMINISTRATOR_GROUP }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BIZTALK_SERVER_OPERATORS_GROUP','{{ VCENTER_BIZTALK_SERVER_OPERATORS_GROUP }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BIZTALK_SERVER_B2B_OPERATORS_GROUP','{{ VCENTER_BIZTALK_SERVER_B2B_OPERATORS_GROUP }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BIZTALK_HOST_USER_GROUP','{{ VCENTER_BIZTALK_HOST_USER_GROUP }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BRUKERNAVN_BIZTALK_HOST_INSTANCE','{{ VCENTER_BRUKERNAVN_BIZTALK_HOST_INSTANCE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml 
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'PASSORD_BIZTALK_HOST_INSTANCE','{{ VCENTER_PASSORD_BIZTALK_HOST_INSTANCE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml
  - name: Lager konfigurasjon for  Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_biz.xml -Raw) -replace 'BIZTALK_ISOLATED_HOST_USER_GROUP','{{ VCENTER_BIZTALK_ISOLATED_HOST_USER_GROUP }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml