---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_shell: “\\pdc\delt\Program Files (x86)\Microsoft BizTalk Server 2016\Configuration.exe” /S \\pdc\delt\BizTalkConfig1.xml
    args:
      executable: cmd