---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install Minimal Biztalk
    win_command: \\pdc\delt\install\BTS_2016_Dev\BizTalkServer\setup.exe /NORESTART /CABPATH \\pdc\delt\install\Biztalk-Deploy-master\bin\BtsRedistW2K12R2EN64\BtsRedistW2K12R2EN64.cab /S \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\features-minimal.xml /L c:\log.txt
  - name: Install Biztalk Powershell Extention
    win_shell: 'C:\windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe .\BizTalkFactory.PowerShell.Extensions.dll'
    args:
      chdir: C:\Program Files (x86)\Microsoft BizTalk Server 2016\SDK\Utilities\PowerShell