---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_shell: 'Configuration.exe /S \\pdc\delt\{{ VCENTER_MILJO }}BizTalkConfig_esso.xml /noprogressbar /L c:\sso-log.txt'
    become: yes
    become_method: runas
    vars:
      ansible_become_user: 'LAB\administrator'
      ansible_become_pass: 'Password123!'
    args:
      chdir: c:\Program Files (x86)\Microsoft BizTalk Server 2016\