---
- name: Install Biztalk 2016
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\BizTalkConfig_esso.xml -Raw) -replace 'servernavn','{{ VCENTER_GUEST_NAME_2 }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'PASSORD_BACKUP_SECRET','{{ VCENTER_PASSORD_BACKUP_SECRET }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'BRUKERNAVN_ENTSSO_SERVICE','{{ VCENTER_BRUKERNAVN_ENTSSO_SERVICE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'DOMENE_NAVN','{{ VCENTER_DOMENE_NAVN }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace 'ENTSSO_PASSORD','{{ VCENTER_ENTSSO_PASSORD }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\BizTalkConfig_esso.xml -Raw) -replace '"C:\Program Files\Common Files\Enterprise Single Sign-On\SSO7C1F.bak"','{{ VCENTER_ENTSSO_BACKUP_SECRET_FILE }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_esso.xml
  - name: Configure Biztalk
    win_shell: ((Get-Content -path \\pdc\delt\install\Biztalk-Deploy-master\BiztalkConfig\BizTalkConfig_biz.xml -Raw) -replace 'servernavn','{{ VCENTER_GUEST_NAME_2 }}') | Set-Content -Path \\pdc\delt\BizTalkConfig_biz.xml