---
# This playbook uses the win_ping module to test connectivity to Windows hosts
- name: Ping 
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: ping
    win_ping:
