---
- name: COnfigure MSDTC
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Configure MSDTC
    win_shell: Set-DtcNetworkSetting –DtcName Local –AuthenticationLevel Mutual –InboundTransactionsEnabled 1 –OutboundTransactionsEnabled 1 –RemoteClientAccessEnabled 1 –confirm:$false