---
- name: Install visualstudio2017enterprise
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install MSSQL
    win_chocolatey:
      name: visualstudio2017enterprise
      state: present