---
- name: Install visualstudio2015community
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Install MSSQL
    win_chocolatey:
      name: visualstudio2015community
      state: present