---
- name: Install Windows Updates
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - win_reboot:
  - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900