---
- name: Install sql-server-management-studio
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 420