---
- name: Install Windows Updates
  hosts: "{{ VCENTER_GUEST_NAME }}.lab.local"

  tasks:
  - name: Windows Update
    win_updates:
    category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
  - name: Windows Reboot
    win_reboot:
    when: update_result.reboot_required